# Generated by Django 6.0 on 2025-12-16 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upskill", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="images"),
        ),
    ]
