# Generated by Django 6.0 on 2025-12-17 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("upskill", "0002_course_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
