# Generated by Django 6.0 on 2025-12-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="email_verification_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
